apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "claims-api.name" . }}-config
  labels:
    {{- include "claims-api.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}