apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "claims-api.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "claims-api-role"
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name | default "claims-api-sa" }}