replicaCount: 1

image:
  tag: "f09a5fd"

env:
  ASPNETCORE_ENVIRONMENT: "Development"
  LOG_LEVEL: "Debug"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi