replicaCount: 2

image:
  tag: "b09b51c"

env:
  ASPNETCORE_ENVIRONMENT: "Production"
  LOG_LEVEL: "Info"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi